name: Build and Deploy code

on:
  # [push, pull_request]
  push:
    branches: ["main"]
  pull_request:
    branches:
      - "test_branch"
      - "main"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: sa hi to Ali
        run: echo "Hello Ali"
