name: Build and Deploy code

on:
  [push, pull_requests]
  # push:
  #   branches: ["main"]
  # pull_requests:
  #   branches:
  #     - "test_branch"
  #     - "main"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: sa hi to Ali
        run: echo "Hello Ali"
